Deleted test files, added tests to yml file

diff --git a/.github/workflows/ci-basic.yml b/.github/workflows/ci-basic.yml
--- a/.github/workflows/ci-basic.yml
+++ b/.github/workflows/ci-basic.yml
@@ -16,8 +16,29 @@ jobs:
                 sudo apt-get update
                 sudo apt-get install -y g++ cmake
 
-            - name: Run test programm
+            - name: Build
               run: |
-                cd tests
-                chmod +x run_test.sh
-                ./run_test.sh
+                cmake -B build
+                cmake --build build
+
+            - name: Tests
+              run: | 
+                ./build/programm hello
+
+                exit_code=$?
+
+                if [ $exit_code -eq 0 ]; then
+                    echo "Test 1 result - OK"
+                else
+                    echo "Test 1 result - FAILURE"
+                fi
+
+                ./build/programm
+
+                exit_code=$?
+
+                if [ $exit_code -eq 1 ]; then
+                    echo "Test 2 result - OK"
+                else
+                    echo "Test 2 result - FAILURE"
+                fi
